### ISSUE TITLE
System.NullReferenceException at System.TimeZoneInfo.IsAdjustmentRuleValid

### ISSUE THREAD

**Issue by sterburg** [redhat-developer/s2i-dotnetcore-ex#10]
I did 
`oc new-app registry.access.redhat.com/dotnet/dotnetcore-10-rhel7~https://github.com/openshift-s2i/s2i-aspnet-example --context-dir=app --name=aspnet-app`

which results in
`# oc logs -f aspnet-app-2-build`
`I0810 15:43:16.614651       1 source.go:197] Downloading "https://github.com/openshift-s2i/s2i-aspnet-example" ...
I0810 15:43:40.233347       1 install.go:251] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I0810 15:43:40.233806       1 install.go:251] Using "run" installed from "<source-dir>/.s2i/bin/run"
I0810 15:43:40.234829       1 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
---> Copying application source ...
---> Installing dependencies ...
## Welcome to .NET Core!

Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
## Telemetry

The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
## Configuring...

A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2649 ms
E0810 15:43:45.245237       1 util.go:91] 
E0810 15:43:45.248820       1 util.go:91] Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.)) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
E0810 15:43:45.248873       1 util.go:91]    at System.TimeZoneInfo.IsAdjustmentRuleValid(AdjustmentRule rule, AdjustmentRule previousRule, DateTime dateTime, DateTime dateOnly, Boolean dateTimeisUtc)
E0810 15:43:45.248906       1 util.go:91]    at System.TimeZoneInfo.GetAdjustmentRuleForTime(DateTime dateTime, Boolean dateTimeisUtc)
E0810 15:43:45.248920       1 util.go:91]    at System.TimeZoneInfo.GetUtcOffset(DateTime time, TimeZoneInfo zone, TimeZoneInfoOptions flags)
E0810 15:43:45.248926       1 util.go:91]    at System.TimeZoneInfo.GetUtcOffset(DateTime dateTime, TimeZoneInfoOptions flags, CachedData cachedData)
E0810 15:43:45.248934       1 util.go:91]    at System.DateTimeOffset..ctor(DateTime dateTime)
E0810 15:43:45.248939       1 util.go:91]    at System.IO.Compression.ZipArchiveEntry..ctor(ZipArchive archive, ZipCentralDirectoryFileHeader cd)
E0810 15:43:45.248946       1 util.go:91]    at System.IO.Compression.ZipArchive.ReadCentralDirectory()
E0810 15:43:45.248951       1 util.go:91]    at System.IO.Compression.ZipArchive.GetEntry(String entryName)
E0810 15:43:45.248955       1 util.go:91]    at Microsoft.DotNet.Archive.IndexedArchive.ExtractSource.CopyToStream(Stream destinationStream)
E0810 15:43:45.248959       1 util.go:91]    at Microsoft.DotNet.Archive.IndexedArchive.CopyOperation.Execute()
E0810 15:43:45.248969       1 util.go:91]    at Microsoft.DotNet.Archive.IndexedArchive.ExtractOperation.DoOperation()
E0810 15:43:45.248980       1 util.go:91]    at Microsoft.DotNet.Archive.IndexedArchive.<>c__DisplayClass19_1.<Extract>b__0(ExtractOperation extractOperation)
E0810 15:43:45.248986       1 util.go:91]    at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
E0810 15:43:45.248992       1 util.go:91]    at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
E0810 15:43:45.248996       1 util.go:91]    at System.Linq.Parallel.SpoolingTaskBase.Work()
E0810 15:43:45.249000       1 util.go:91]    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
E0810 15:43:45.249004       1 util.go:91]    at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
E0810 15:43:45.249009       1 util.go:91]    at System.Threading.Tasks.Task.Execute()
E0810 15:43:45.249013       1 util.go:91]    --- End of inner exception stack trace ---
E0810 15:43:45.249020       1 util.go:91]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
E0810 15:43:45.249025       1 util.go:91]    at System.Linq.Parallel.MergeExecutor`1.Execute()
E0810 15:43:45.249029       1 util.go:91]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
E0810 15:43:45.249034       1 util.go:91]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
E0810 15:43:45.249049       1 util.go:91]    at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
E0810 15:43:45.249062       1 util.go:91]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
E0810 15:43:45.249067       1 util.go:91]    at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
E0810 15:43:45.249074       1 util.go:91]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
E0810 15:43:45.249079       1 util.go:91]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
E0810 15:43:45.249085       1 util.go:91]    at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
E0810 15:43:45.249090       1 util.go:91]    at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
E0810 15:43:45.249096       1 util.go:91]    at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
E0810 15:43:45.249103       1 util.go:91]    at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
E0810 15:43:45.249108       1 util.go:91]    at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
E0810 15:43:45.249115       1 util.go:91]    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
E0810 15:43:45.249120       1 util.go:91]    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
E0810 15:43:45.249126       1 util.go:91]    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
E0810 15:43:45.249132       1 util.go:91]    at Microsoft.DotNet.Cli.Program.Main(String[] args)
E0810 15:43:45.516540       1 util.go:91] /usr/libexec/s2i/assemble: line 9:    15 Aborted                 (core dumped) dotnet restore
`

I am using:
OS: Fedora-24
Docker: 1.10.3
Timezone: CEST

**Comment by sabre1041** [comment]
@sterburg Built successfully in Red Hat CDK 2.1. Could be related to this [bug](https://github.com/dotnet/cli/issues/3681)

Can you see if that may apply?

**Comment by jerboaa** [comment]
This has been fixed with an image update (dotnet/dotnetcore-10-rhel7) since. It's been fixed in dotnet included in the image update. That was fixed in rh-dotnetcore10-dotnetcore-1.0.1 I believe. Please reopen if you are still seeing this issue.
