### ISSUE TITLE
As a best practice, shouldn't all apps start with at least 2 containers?

### ISSUE THREAD

**Issue by alberttwong** [redhat-developer/s2i-dotnetcore-ex#11]
Moving from https://github.com/openshift-s2i/s2i-aspnet/issues/19

**Comment by alberttwong** [comment]
What is the standard for other RH examples?

**Comment by jerboaa** [comment]
I don't know if there is best practices. Looking at the [rails-example](https://github.com/openshift/rails-ex/blob/master/openshift/templates/rails-postgresql.json#L180) it seems it's 1 pod. It makes some sense as scaling should be fairly easy to do via the OpenShift webconsole. Either way, this would have to go into the template. I'm not sure this is supported via the image stream example (try it) mechanism.

**Comment by tmds** [comment]
Closing old issues.
