### ISSUE TITLE
Implement example of limits and quota

### ISSUE THREAD

**Issue by alberttwong** [redhat-developer/s2i-dotnetcore-ex#12]
I thought the limit and quotas would be a good best practice. We can make it high but I'm leaning to putting in something so that it's just not unbounded. 

Moving from https://github.com/openshift-s2i/s2i-aspnet/issues/13

**Comment by alberttwong** [comment]
What is the standard with other RH examples?

**Comment by jerboaa** [comment]
Memory limit example: https://github.com/openshift/rails-ex/blob/master/openshift/templates/rails-postgresql.json#L460
This example does not [persist data across container restarts](https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/master/app/Startup.cs#L44), so quota (as in disk-space quota) does not make sense, IMHO.

**Comment by jerboaa** [comment]
I've just noticed that if created via the template a memory limit is in place:
https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/master/templates/aspnet-s2i-template.json#L203

Not sure what else there is to do. I'm closing this for now. Feel free to reopen if you think there is still something missing.
