### ISSUE TITLE
Couldn't find 'project.json' in '.'

### ISSUE THREAD

**Issue by dwojciec** [redhat-developer/s2i-dotnetcore-ex#16]
By executing the command : oc new-app registry.access.redhat.com/dotnet/dotnetcore-10-rhel7~https://github.com/openshift-s2i/s2i-aspnet-example --name=aspnet-app we are receiving the error :
log  : Restore completed in 76090ms.
---> Building application from source ...
Couldn't find 'project.json' in '.'

error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnetcore-10-rhel7@sha256:fc6ab7bb67b05cc42a0be9e01dbfdc45baeea7b3bb82fa57634be6a26bd89d47

The error is due because the directory of the application (app directory is not mentioned as the Source Context Dir for the code). 
By editing the build config and adding app for Source Context Dir and rebuild it it's working fine.
If I'm importing the template and I'm using it it's working fine because app is mentioned for "Source Context Dir".
Thanks you for your work

**Comment by dwojciec** [comment]
Bu using  --context-dir=app at the end of the command it's working fine.

The correct command is 
oc new-app registry.access.redhat.com/dotnet/dotnetcore-10-rhel7~https://github.com/openshift-s2i/s2i-aspnet-example --name=aspnet-app --context-dir=app

**Comment by jerboaa** [comment]
@dwojciec yes, thanks. We'll be moving this repository to redhat-developer/s2i-dotnetcore-ex and will fix the README.
