### ISSUE TITLE
Revert explicit config for listening on 8080

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/s2i-dotnetcore-ex#20]
Once a new redhat-developer/s2i-dotnetcore image is released and openshift-s2i/s2i-aspnet supports something similar to https://github.com/redhat-developer/s2i-dotnetcore/pull/34 we can revert https://github.com/redhat-developer/s2i-dotnetcore-ex/commit/6f2f0fd931d648efa9970d50f2dfc3564944bdcd#diff-729af9bfa292ba655a6e0b1452e17dfa

**Comment by jerboaa** [comment]
FWIW, updated dotnet/dotnetcore-1x-rhel7 images are in the registry now.

**Comment by tmds** [comment]
Closing old issues.
