### ISSUE TITLE
OpenShift CDK v3.4 certificate error prevents build

### ISSUE THREAD

**Issue by stevef1uk** [redhat-developer/s2i-dotnetcore-ex#25]
Hi,

I was trying this sample app plus another I found a blog post on (http://www.arctiq.ca/our-blog/2016/10/2/7bepjjxhags4s130f2c9ggks5d4xjo) and found the same errors. Running on a Mac (10.12.3) with OpenShift CDK v3.4:

oc version
oc v3.4.1.2
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://10.1.2.2:8443
openshift v3.3.1.5
kubernetes v1.3.0+52492b4

[vagrant@rhel-cdk ~]$ uname -a
Linux rhel-cdk 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

Seems to be that there is a certificate error, but I don't know how to resolve. Any advice appreciated.

Cloning "https://github.com/openshift-s2i/s2i-aspnet-example" ...
	Commit:	8b52d564fbb8f499406fd9428e6f6d1292bd6078 (Set DOTNET_NPM_TOOLS environment. (#19))
	Author:	Severin Gehwolf <jerboaa@gmail.com>
	Date:	Fri Jan 27 09:59:04 2017 +0100

---> Copying application source ...
---> Installing dependencies ...
log  : Restoring packages for /opt/app-root/src/project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Peer certificate cannot be authenticated with given CA certificates

error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnetcore-10-rhel7@sha256:fc6ab7bb67b05cc42a0be9e01dbfdc45baeea7b3bb82fa57634be6a26bd89d47

**Comment by jerboaa** [comment]
This seems to be an issue with the CDK. Please file a bug report with them here:
https://issues.jboss.org/projects/CDK/issues/

It would be interesting to see whether plain curl on that URL works:

    $ curl https://api.nuget.org/v3/index.json

**Comment by stevef1uk** [comment]
Yes, thanks. Recreated the CDK vagrant image and it works now. 
Thanks for looking.
