### ISSUE TITLE
dotnetcore-2.0 branch

### ISSUE THREAD

**Issue by tmds** [redhat-developer/s2i-dotnetcore-ex#28]
We need to create the 2.0 version of this example.

CC @jerboaa @aslicerh @omajid

**Comment by jerboaa** [comment]
Yes :)

**Comment by jerboaa** [comment]
Issue #30 updates the docs. Once that's merged we can push `master` as `dotnetcore-2.0` branch.

**Comment by jerboaa** [comment]
Pushed: https://github.com/redhat-developer/s2i-dotnetcore-ex/tree/dotnetcore-2.0
