### ISSUE TITLE
 Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -97 EAFNOSUPPORT address family not supported

### ISSUE THREAD

**Issue by ckayfish** [redhat-developer/s2i-dotnetcore-ex#3]
Fisrt, thank you very much for this example.

My pod kept crashing when trying to run this application giving me the subject Exception error. I resolved this in our enterprise Origins instance, after discovering people having similar issues that seems related to port binding in Kestrel. https://github.com/aspnet/KestrelHttpServer/issues/766

I'm not suggesting what the best fix for everyone is, but what worked for me was editing my host var in Program.cs and adding this right before .build(); `.UseUrls("http://0.0.0.0:5000")`

**Comment by ckayfish** [comment]
This is probably best handled at the docker OS layer (https://github.com/docker/docker/issues/2174) or at the Kestrel level. Both of these would be part of the s2i-aspnet package, so really I was just sharing my work-around, and asking for feedback on best way to approach this. Perhaps an open Issue in this repo isn't the best place to have this ongoing discussion, but hopefully it can serve help anyone else wanting an easy way to see .Net core on Linux in a PaaS run in their ecosystem.

**Comment by jawnsy** [comment]
@ckayfish Hey Curtis, thanks for filing this issue, providing information about your workaround, as well as references to the aspnet and docker bugs. I think this issue is a great way to discuss the problem and its solution; we just need some time to investigate and we'll update the issue with comments. cc @sabre1041

**Comment by sabre1041** [comment]
@ckayfish the team made a number of changes recently to the base image as well as this example application to account for the .NET Core 1.0 release

**Comment by jerboaa** [comment]
Closing as per @sabre1041's comment.
