### ISSUE TITLE
Update to 2.0.0 

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-dotnetcore-ex#31]
`app.csproj` refers to the version`2.0.0-preview2-final`. We should update this to `2.0.0` to work with the final release.

**Comment by tmds** [comment]
This will work fine when published with the msbuild property to disable the asp net store. To update, replace everything under the app folder with an invocation of 'dotnet new mvc' with a 2.0.0 sdk.

**Comment by jerboaa** [comment]
Closed with #32.

**Comment by omajid** [comment]
Thanks!
