### ISSUE TITLE
Missing frontend dependencies

### ISSUE THREAD

**Issue by jsvgoncalves** [redhat-developer/s2i-dotnetcore-ex#7]
When on `Development` mode, the app is missing CSS and JS files which should be fetched by running `$ bower install`. On `Production` mode the CSS and JS (jquery, bootstrap..) are fetched using the official CDN versions.

This should be handled by https://github.com/openshift-s2i/s2i-aspnet/blob/master/s2i/assemble as to follow other examples, such as https://github.com/sclorg/s2i-python-container/blob/master/3.5/s2i/bin/assemble.

**Comment by alberttwong** [comment]
@jsvgoncalves Is this issue still open?

**Comment by jsvgoncalves** [comment]
@alberttwong yeah, a bit busy atm so I'll fix this later if it's still around.

**Comment by jerboaa** [comment]
The current (yet unreleased) version of https://github.com/redhat-developer/s2i-dotnetcore handles this by installing them via [npm](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.0/s2i/bin/assemble#L17).

**Comment by jerboaa** [comment]
FYI: Updated images have been released which have npm available. We should be able to fix this properly.

**Comment by jsvgoncalves** [comment]
@jerboaa thanks for the info. Are we automatically doing `bower install` (or npm directly or whatever other alternative) on these images or should we manually include it on the deployment script?

**Comment by jerboaa** [comment]
@jsvgoncalves npm is available and required tools can be installed by setting the DOTNET_NPM_TOOLS environment variable. Then it's a matter of what's in publish options in project.json[1]. See:

https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.1/test/run#L387
https://github.com/redhat-developer/s2i-dotnetcore/blob/master/1.1/test/newweb/.s2i/environment

[1] https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/master/app/project.json#L104

**Comment by tmds** [comment]
Closing old issues.
